name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adoptopenjdk'
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}/.m2

    - name: Create Maven settings.xml
      run: |
        mkdir -p ${{ github.workspace }}/.m2
        echo '<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.TOKEN }}</password>
            </server>
          </servers>
        </settings>' > ${{ github.workspace }}/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy -s ${{ github.workspace }}/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
